# Numpy tutorial in Chinese

In [2]:
import numpy as np

## 理解 Numpy
---
### 什么是 Numpy？
NumPy是一个功能强大的Python库，主要用于对多维数组执行计算。 NumPy 来源于两个单词 **Numerical** 和 **Python**。NumPy提供了大量的库函数和操作，可以帮助程序员轻松地进行数值计算。这类数值计算广泛用于以下任务：
</br>
- **机器学习模型**：在编写机器学习算法时，需要对矩阵进行各种数值计算。例如矩阵乘法、换位、加法等。NumPy提供了一个非常好的库，用于简单(在编写代码方面)和快速(在速度方面)计算。NumPy数组用于存储训练数据和机器学习模型的参数。
- **图像处理和计算机图形学**：计算机中的图像表示为多维数字数组。NumPy成为同样情况下最自然的选择。实际上，NumPy提供了一些优秀的库函数来快速处理图像。例如，镜像图像、按特定角度旋转图像等。
- **数学任务**： NumPy对于执行各种数学任务非常有用，如数值积分、微分、内插、外推等。因此，当涉及到数学任务时，它形成了一种基于Python的MATLAB的快速替代。

### NumPy 中的数组
NumPy提供的最重要的数据结构是一个称为NumPy数组的强大对象。NumPy数组是通常的Python数组的扩展。NumPy数组配备了大量的函数和运算符，可以帮助我们快速编写上面讨论过的各种类型计算的高性能代码。
</br>
- .shape ： 输出数组的维度， 返回值类型为*tuple*
```python
np_array.shape
```
- [index：index]索引 : 输出切片后的数组， 返回值类型为*np array*或者*具体的值*
```python
#返回index=0时，array的值
my_array[0]
#返回index0到1的切片，返回值为array（左闭右开）
my_array[0:1]
#返回完整的array，常用于array的copy
my_array[:]
#二维数组的第二列
my_2d_array[:, 1]
```
- np.zeros() 和 np.ones() : 创建一个numpy array，并用*o*或者*1*填充
```python
#创建一个长度为5的，用0填充的一维数组
my_new_array = np.zeros((5))
#创建一个2x3，用1填充的二维数组
my_2d_array = np.zeros((2, 3))
#创建一个用随机数填充的二维数组
my_2d_array = np.random.random((2, 3))
```

### NumPy中的数组操作
---
使用NumPy，你可以轻松地在数组上执行数学运算。例如，你可以添加NumPy数组，你可以减去它们，你可以将它们相乘，甚至可以将它们分开。 以下是一些例子：
```python
a = np.array([[1.0, 2.0], [3.0, 4.0]]) 
b = np.array([[5.0, 6.0], [7.0, 8.0]]) 
sum = a + b 
difference = a - b
#乘法运算符执行逐元素乘法而不是矩阵乘法
product = a * b 
#矩阵乘法
matrix_product = a.dot(b)
quotient = a / b 
```

### 为什么要使用NumPy
---
NumPy是Python中的一个运算速度非常快的一个数学库，它非常重视数组。它允许你在Python中进行向量和矩阵计算，***并且由于许多底层函数实际上是用C编写的***，因此你可以体验在原生Python中永远无法体验到的速度。

### 创建数组
---
- **多维数组**： 为了创建一个2D（二维）数组，我们传递一个列表的列表（或者是一个序列的序列）给array()函数。如果我们想要一个3D（三维）数组，我们就要传递一个列表的列表的列表

In [3]:
# 创建一维数组
a = np.array([0, 1, 2, 3, 4])
#你可以传递任何序列（类数组），而不仅仅是常见的列表（list）数据类型。
b = np.array((0, 1, 2, 3, 4))
c = np.arange(5)
d = np.linspace(0, 2*np.pi, 5)

print(a) # >>>[0 1 2 3 4]
print(b) # >>>[0 1 2 3 4]
print(c) # >>>[0 1 2 3 4]
#当我们打印具有不同长度数字的数组时，它会自动将它们填充出来
print(d) # >>>[ 0.          1.57079633  3.14159265  4.71238898  6.28318531]
print(a[3]) # >>>3

[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4]
[0.         1.57079633 3.14159265 4.71238898 6.28318531]
3


In [4]:
# 二维数组
a = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28 ,29, 30],
              [31, 32, 33, 34, 35]])
#三行五列
print(a[2,4]) # >>>25

25


### Jupyter notebook表示向量与矩阵